In [1]:
import json
# ============================================================================
# RF2-F — hybrid cascade candidate synthesis   (D plane, NON_CANONICAL)
# 이 노트북은 결과를 만들지 않는다. tools/rf2_f_cascade_synthesis.py 가 만든
# results/RF2_F_cascade_candidates.json 을 읽어 표와 그림으로 렌더할 뿐이다.
# 이 노트북은 A~E 의 산출물을 읽기만 하고 수정하지 않는다.
# ============================================================================
META = {
    "research_question": "RQ-D-RF-002 / D-RF2-F — A~E 를 종합해 2~3개 candidate measurement architecture 를 조건과 대가와 함께 제시한다. best model 을 고르지 않고 threshold 를 정하지 않는다.",
    "child_id": "D-RF2-F",
    "parent_rq_id": "RQ-D-RF-002",
    "hypothesis_id": "H-RF2-F-CASCADE-SYNTHESIS",
    "competing_hypotheses": [
        "H1 rule-only",
        "H2 rule + semantic prototype + margin abstain",
        "H3 hierarchical + field-specific semantic",
        "H4 (추가) admissibility gate + semantic only"
    ],
    "output_kind": "RECOMMENDED_EXPERIMENTAL_CANDIDATES",
    "D_FACT_01": "prior_archetype 과 prior_business_domain 은 이 56 표본에서 완전 전단사(nMI=1.000, 56/56). 따라서 모든 prior_agreement 는 업종 배정 재현율이며 정확도가 아니다.",
    "input_snapshot_sha": {
        "results/D_OBSERVATION_TABLE_v2.csv": "c39c10f09f7a6a7603409550eb331612eb44634eb98ec387a604aa5221351e6b",
        "results/D_TEXT_CORPUS_v2.csv": "bf6bb772faa45541c780c75f5cbffa856783a34661a84e3de27a9eb5da4ea36a",
        "results/RF2_A_rule_firing.json": "189a1ba7232cd5897d62d4a2e1e9ebbd230a0e20683f6c630e95eaf693b7d5bd",
        "results/RF2_B_feature_discriminability.json": "61f5df5e356cc20e52c4ab43c8b2409741795696682e6c6dab7f468cfc86d131",
        "results/RF2_C_field_ablation.json": "1ad4bdec4cc72208a4ed48e0ef8709d096cc44451a624f3cc3f692129971c896",
        "results/RF2_D_hierarchical.json": "306557bfa4289e6105124fed54cc562988422cd906518e95c5fe1f11d244b976",
        "results/RF2_E_abstention_taxonomy.json": "eaab14e60ea5b7e34fe77ac161672eb79e86b89c945c8a3a0e7139a35d0baec4"
    },
    "child_result_sha": {
        "results/RF2_A_rule_firing.json": "189a1ba7232cd5897d62d4a2e1e9ebbd230a0e20683f6c630e95eaf693b7d5bd",
        "results/RF2_B_feature_discriminability.json": "61f5df5e356cc20e52c4ab43c8b2409741795696682e6c6dab7f468cfc86d131",
        "results/RF2_C_field_ablation.json": "1ad4bdec4cc72208a4ed48e0ef8709d096cc44451a624f3cc3f692129971c896",
        "results/RF2_D_hierarchical.json": "306557bfa4289e6105124fed54cc562988422cd906518e95c5fe1f11d244b976",
        "results/RF2_E_abstention_taxonomy.json": "eaab14e60ea5b7e34fe77ac161672eb79e86b89c945c8a3a0e7139a35d0baec4"
    },
    "code_sha": {
        "tools/rf2_f_cascade_synthesis.py": "4de9f2e7290a02ae98cba15ceb437441bf368dcd1b8f2b284901c0e5b817bd4a"
    },
    "result_sha": {
        "results/RF2_F_cascade_candidates.json": "c6ac3e61a1e219bfe5be0443dac154a99abe773f18a4bf86e405c722b9454602"
    },
    "mlflow": {
        "run_id": "3aa6b7dfb6c8444d8187c0c8f43e186b",
        "parent_run_id": "ae754858ba3a4be391e5f811640d3fd8",
        "experiment": "LA_03_RF_MAPPING",
        "superseded_run": "155dda8e001246f7995bcc316a7479ed (SUPERSEDED — perm 수만 다른 사전 실행)"
    },
    "n": {
        "targets_in_mart": 56,
        "n_expected": 56
    },
    "grain": "target (wtg), in_mart == 1",
    "seed": 20260827,
    "n_permutations": 20000,
    "verdict": "PARTIALLY_SUPPORTED",
    "firewall_not_opened": [
        "holdout label",
        "LABEL_SPLIT_FROZEN*",
        "HOLDOUT_FOR_C*",
        "RAW_L1~L4*",
        "PACKET_L*",
        "*_OVERLAP*",
        "PRECEDENCE_CONTESTED*",
        "CALIBRATION_FOR_B*",
        "**/control/**",
        "B/C target-level holdout error report"
    ]
}
for k, v in META.items():
    print(f"{k:<22} {v if not isinstance(v, (dict, list)) else json.dumps(v, ensure_ascii=False)[:150]}")

research_question      RQ-D-RF-002 / D-RF2-F — A~E 를 종합해 2~3개 candidate measurement architecture 를 조건과 대가와 함께 제시한다. best model 을 고르지 않고 threshold 를 정하지 않는다.
child_id               D-RF2-F
parent_rq_id           RQ-D-RF-002
hypothesis_id          H-RF2-F-CASCADE-SYNTHESIS
competing_hypotheses   ["H1 rule-only", "H2 rule + semantic prototype + margin abstain", "H3 hierarchical + field-specific semantic", "H4 (추가) admissibility gate + semantic
output_kind            RECOMMENDED_EXPERIMENTAL_CANDIDATES
D_FACT_01              prior_archetype 과 prior_business_domain 은 이 56 표본에서 완전 전단사(nMI=1.000, 56/56). 따라서 모든 prior_agreement 는 업종 배정 재현율이며 정확도가 아니다.
input_snapshot_sha     {"results/D_OBSERVATION_TABLE_v2.csv": "c39c10f09f7a6a7603409550eb331612eb44634eb98ec387a604aa5221351e6b", "results/D_TEXT_CORPUS_v2.csv": "bf6bb772fa
child_result_sha       {"results/RF2_A_rule_firing.json": "189a1ba7232cd5897d62d4a2e1e9ebbd230a0e20683f6c630e95eaf693b7d5bd", "results/RF2_B_feature_discriminability.json":
code_sha               {"tools/rf2_f_cascade_synthesis.py": "4de9f2e7290a02ae98cba15ceb437441bf368dcd1b8f2b284901c0e5b817bd4a"}
result_sha             {"results/RF2_F_cascade_candidates.json": "c6ac3e61a1e219bfe5be0443dac154a99abe773f18a4bf86e405c722b9454602"}
mlflow                 {"run_id": "3aa6b7dfb6c8444d8187c0c8f43e186b", "parent_run_id": "ae754858ba3a4be391e5f811640d3fd8", "experiment": "LA_03_RF_MAPPING", "superseded_run"
n                      {"targets_in_mart": 56, "n_expected": 56}
grain                  target (wtg), in_mart == 1
seed                   20260827
n_permutations         20000
verdict                PARTIALLY_SUPPORTED
firewall_not_opened    ["holdout label", "LABEL_SPLIT_FROZEN*", "HOLDOUT_FOR_C*", "RAW_L1~L4*", "PACKET_L*", "*_OVERLAP*", "PRECEDENCE_CONTESTED*", "CALIBRATION_FOR_B*", "**

In [2]:
from pathlib import Path
import hashlib, json
import pandas as pd
pd.set_option("display.width", 220); pd.set_option("display.max_colwidth", 90)

RD = Path("/home/sieg/projects-wsl/ProjectFinal/.agent_worktrees/claude_d_research/"
          "research/landing_accessibility/research_d")
RES = RD / "results"
O = json.loads((RES / "RF2_F_cascade_candidates.json").read_text(encoding="utf-8"))

# --- 무결성: META 의 sha 와 디스크가 일치하는가 (A~E 산출물 포함) ---
for rel, want in {**META["input_snapshot_sha"], **META["code_sha"], **META["result_sha"]}.items():
    got = hashlib.sha256((RD / rel).read_bytes()).hexdigest()
    assert got == want, f"sha mismatch: {rel}"
assert O["verdict"] == META["verdict"]
assert O["n_observed"] == META["n"]["targets_in_mart"] == 56
assert O["best_model_selected"] is False
assert O["production_threshold_declared"] is False
assert "recommended_experimental_candidates" in O and "verdict" in O
print("integrity OK — inputs / A~E results / code / result all match META")
print("verdict:", O["verdict"])
print("output_kind:", O["output_kind"], "| go_nogo:", O["go_nogo_decision"])

integrity OK — inputs / A~E results / code / result all match META
verdict: PARTIALLY_SUPPORTED
output_kind: RECOMMENDED_EXPERIMENTAL_CANDIDATES | go_nogo: NOT_IN_SCOPE — D 는 GO/NO-GO 를 내지 않는다

## 0. D-FACT-01 — 이 문서의 모든 수치가 무엇을 재는가

In [3]:
f = O["D_FACT_01_framing"]
for k, v in f.items():
    print(f"[{k}]\n{v}\n")

[statement]
이 56 target 표본에서 prior_archetype 과 prior_business_domain 은 완전 전단사다 (7↔7, MI = H = 2.311 bits, 정규화 MI = 1.000, 56/56).

[consequence]
A~E 와 이 문서가 보고하는 모든 prior_agreement 는 **업종 배정 재현율**이지 대표기능 정확도가 아니다. 이 문서는 어떤 후보의 기대성능도 '정확도'로 서술하지 않는다.

[source]
results/D_FACT_01_prior_domain_bijection.md

## 1. A~E 요약 — 각 child 의 verdict

In [4]:
for cid, v in O["child_verdicts"].items():
    print(f"[{v['verdict']:<20}] {cid}")
    print(f"    {v['headline']}\n")

[SUPPORTED           ] D-RF2-A
    STRONG multi 30/56 > single 13/56, WEAK+ multi 50/56. exclusivity 7개 중 6개가 0.000, WEAK+ Jaccard 가 0.364 아래인 쌍이 하나도 없다. 유일 STRONG = prior 는 1/56.

[PARTIALLY_SUPPORTED ] D-RF2-B
    16 feature 중 BH-FDR(q<0.10) 통과 0개, 8개는 permutation null 평균 미달. 실효차원 6.37(독립 null 12.51). 상위는 구조량 accessible_name_richness MI 0.264.

[PARTIALLY_SUPPORTED ] D-RF2-C
    primary_controls 0.254 / accessibility_text 0.224 vs text_blob 0.509 — 절반 이하. 브랜드 마스킹 후 title 0.559→0.357, text_blob 0.478 로 1위.

[NOT_SUPPORTED       ] D-RF2-D
    계층 이득 0. McNemar b=0, c=0. 병목은 L1(40건 손실), L2 손실 0.

[PARTIALLY_SUPPORTED ] D-RF2-E
    NO_STRONG_CANDIDATE 는 증상 — 무발화 12 중 11 설명됨. force-map 불일치 rule 0.750 / first-match 0.775 / semantic 0.375. margin 2~3분위 사이 꺾임.

## 2. 판정 일치·불일치 행렬 — 같은 SSOT 규칙, 세 lexicon

In [5]:
am = O["decision_agreement_matrix"]
print("columns:", am["columns"], "  n =", am["n"], "\n")
display(pd.DataFrame(am["pairs"]).set_index(["a", "b"]))

columns: ['A_rule', 'D_flat', 'D_hier', 'E_ruleDT', 'E_admissible', 'SEM_margin']   n = 56

                           both_determined  both_abstain  a_only  b_only  raw_agreement  cohen_kappa  jaccard_determined
a            b
A_rule       D_flat                      3            32      10      11         0.6250      -0.0244              0.1250
             D_hier                      3            30      10      13         0.5893      -0.0662              0.1154
             E_ruleDT                    1            33      12      10         0.6071      -0.1645              0.0435
             E_admissible                3            37      10       6         0.7143       0.1022              0.1579
             SEM_margin                  7            16       6      27         0.4107      -0.0572              0.1750
D_flat       D_hier                     14            40       0       2         0.9643       0.9091              0.8750
             E_ruleDT                    4            35      10       7         0.6964       0.1282              0.1905
             E_admissible                3            36      11       6         0.6964       0.0811              0.1500
             SEM_margin                  8            16       6      26         0.4286      -0.0323              0.2000
D_hier       E_ruleDT                    4            33      12       7         0.6607       0.0828              0.1739
             E_admissible                3            34      13       6         0.6607       0.0432              0.1364
             SEM_margin                  9            15       7      25         0.4286      -0.0467              0.2195
E_ruleDT     E_admissible                3            39       8       6         0.7500       0.1497              0.1765
             SEM_margin                  8            19       3      26         0.4821       0.0835              0.2162
E_admissible SEM_margin                  5            18       4      29         0.4107      -0.0290              0.1316

In [6]:
m = O["rule_implementation_multiplicity"]
print(m["note"], "\n")
print("확정 다중도 (A / D_flat / E_ruleDT):", m["n_implementations_determining_distribution"])
print("합집합:", m["union_determined_by_at_least_one"], " 교집합:", m["determined_by_all_three"])
print("\n2개 이상이 확정한 target:")
display(pd.DataFrame(m["multi_implementation_cases"]))
print("\n구현별 업종 배정 재현율 (확정 구간 조건부):")
display(pd.DataFrame(m["per_implementation_prior_agreement"]).T)

A / D_flat / E_ruleDT 는 SSOT 01 §5·§6 의 **같은 규칙**을 서로 다른 lexicon 으로 독립 조작화한 세 구현이다. 아래 수치는 '어느 target 이 결정 가능한가' 가 target 의 성질인지 lexicon 의 성질인지를 가른다.

확정 다중도 (A / D_flat / E_ruleDT): {'0': 25, '1': 25, '2': 5, '3': 1}
합집합: 31  교집합: 1

2개 이상이 확정한 target:

                wtg  service         prior_archetype                                                preds  same_leaf
0  22ffba7a86ea9919     코스트코             ITEM_DETAIL                         {'D': 'QUERY', 'E': 'QUERY'}       True
1  4feab7e61bf642e8   CJ온스타일             ITEM_DETAIL           {'A': 'QUERY', 'D': 'QUERY', 'E': 'QUERY'}       True
2  ea031f85e857140e     메가커피             ITEM_DETAIL                         {'D': 'QUERY', 'E': 'QUERY'}       True
3  35319a420294ee17       토스  FINANCIAL_ACTION_ENTRY  {'A': 'ITEM_DETAIL', 'D': 'FINANCIAL_ACTION_ENTRY'}      False
4  24e6654bfd1ab85b  YouTube            CONTENT_OPEN                         {'A': 'QUERY', 'D': 'QUERY'}       True
5  95e22b9aff7196b3    NS홈쇼핑             ITEM_DETAIL             {'D': 'ITEM_DETAIL', 'E': 'ITEM_DETAIL'}       True

구현별 업종 배정 재현율 (확정 구간 조건부):

         n_determined n_prior_agree prior_agreement prior_agreement_wilson95 prior_agreement_of_56
A_rule             13             1          0.0769         [0.0137, 0.3331]                0.0179
D_flat             14             5          0.3571         [0.1634, 0.6124]                0.0893
E_ruleDT           11             6          0.5455         [0.2801, 0.7873]                0.1071

In [7]:
print("6개 컬럼이 만장일치가 아닌 target:", len(O["split_targets"]), "/ 56")
sp = pd.DataFrame(O["split_targets"])
display(sp[["service", "prior_archetype", "determined_by", "n_rule_impl_determining", "E_sem_margin"]].head(20))
print("\n사유 예시:")
for s in O["split_targets"][:5]:
    print(" ", s["service"], "->", s["reasons"])

6개 컬럼이 만장일치가 아닌 target: 46 / 56

     service         prior_archetype                                     determined_by  n_rule_impl_determining  E_sem_margin
0       쿠팡이츠             ITEM_DETAIL                                          [A_rule]                        1       0.00120
1       삼성카드  FINANCIAL_ACTION_ENTRY                                      [SEM_margin]                        0       0.03329
2       GS25             ITEM_DETAIL                              [D_hier, SEM_margin]                        0       0.02078
3       코스트코             ITEM_DETAIL            [D_flat, D_hier, E_ruleDT, SEM_margin]                        2       0.01825
4     TikTok            CONTENT_OPEN                                  [D_flat, D_hier]                        1       0.01263
5         티맵            PLACE_LOOKUP                              [A_rule, SEM_margin]                        1       0.03273
6   신한 SOL뱅크  FINANCIAL_ACTION_ENTRY                                      [SEM_margin]                        0       0.04846
7         밴드     COMMUNICATION_ENTRY                      [D_flat, D_hier, SEM_margin]                        1       0.08727
8      세븐일레븐             ITEM_DETAIL                              [A_rule, SEM_margin]                        1       0.03574
9         다음                   QUERY                                      [SEM_margin]                        0       0.02208
10    KB Pay  FINANCIAL_ACTION_ENTRY                      [D_flat, D_hier, SEM_margin]                        1       0.05577
11      카카오T            PLACE_LOOKUP                              [A_rule, SEM_margin]                        1       0.01668
12   디바이스 케어           UTILITY_ENTRY                                      [SEM_margin]                        0       0.01714
13     롯데백화점             ITEM_DETAIL                [A_rule, E_admissible, SEM_margin]                        1       0.04340
14      마켓컬리             ITEM_DETAIL                                      [SEM_margin]                        0       0.07815
15   Netflix            CONTENT_OPEN                    [D_flat, D_hier, E_admissible]                        1       0.00039
16       다이소             ITEM_DETAIL                                        [E_ruleDT]                        1       0.00657
17    CJ온스타일             ITEM_DETAIL  [A_rule, D_flat, D_hier, E_ruleDT, E_admissible]                        3       0.00967
18      홈앤쇼핑             ITEM_DETAIL                            [E_ruleDT, SEM_margin]                        1       0.04362
19    Chrome                   QUERY                                      [SEM_margin]                        0       0.03658

사유 예시:
  쿠팡이츠 -> ['rule lexicon 조작화 차이 (같은 SSOT §5, 다른 어휘·임계)', 'rule 은 유일 후보를 냈으나 semantic top1-top2 가 붙어 있음', "E: 표면부재 계열 유형 보유 ['T05_GENERIC_BRAND_LANDING', 'T06_APP_INSTALL_SURFACE']"]
  삼성카드 -> ['semantic margin 은 높은데 어떤 rule 구현도 발화하지 않음', "E: 관측손상 계열 유형 보유 ['T10B_TEXT_CAP_TRUNCATION', 'T11_OVERLAY_OBSTRUCTED']"]
  GS25 -> ['계층 L1 이 flat 이 못 닫은 것을 닫음 (D-RF2-D §11.1: 2건, 둘 다 prior 불일치)', 'semantic margin 은 높은데 어떤 rule 구현도 발화하지 않음', "E: 표면부재 계열 유형 보유 ['T05_GENERIC_BRAND_LANDING']"]
  코스트코 -> ['rule lexicon 조작화 차이 (같은 SSOT §5, 다른 어휘·임계)', "E: 관측손상 계열 유형 보유 ['T10B_TEXT_CAP_TRUNCATION']"]
  TikTok -> ['rule lexicon 조작화 차이 (같은 SSOT §5, 다른 어휘·임계)', 'rule 은 유일 후보를 냈으나 semantic top1-top2 가 붙어 있음', "E: 표면부재 계열 유형 보유 ['T06_APP_INSTALL_SURFACE']", "E: 관측손상 계열 유형 보유 ['T11_OVERLAY_OBSTRUCTED']"]

![decision matrix](../../research_d/figures/RF2_F_decision_matrix.png)
![agreement](../../research_d/figures/RF2_F_agreement_matrix.png)

## 3. coverage 를 맞춘 cascade vs semantic-only
> y 축은 **정확도가 아니라 업종 배정 재현율**이다 (D-FACT-01). threshold 는 선언하지 않는다.

In [8]:
c = O["matched_coverage_comparison"]
print(c["note"], "\n")
display(pd.DataFrame(c["curve"]).head(14))
print("\ncascade 가 semantic-only 를 한 번도 못 이긴다:", c["cascade_never_beats_semantic_only_at_matched_coverage"])
print("\nrule 이 확정한 11건에서의 짝 대조:")
print(json.dumps(c["paired_on_rule_mapped_11"], ensure_ascii=False, indent=1))

모든 prior_agreement 는 D-FACT-01 에 따라 **업종 배정 재현율**이다. 이 표는 threshold 를 선언하지 않는다. coverage 를 맞춘 대조일 뿐이다.

    coverage_n  coverage  semantic_only_prior_agreement semantic_only_wilson95  semantic_only_debranded_prior_agreement  rule_first_cascade_prior_agreement rule_first_cascade_wilson95  delta_cascade_minus_semantic_only
0           56    1.0000                         0.6786        [0.5482, 0.786]                                   0.6964                              0.6429            [0.5119, 0.7554]                            -0.0357
1           54    0.9643                         0.6852       [0.5526, 0.7932]                                   0.6852                              0.6481            [0.5148, 0.7618]                            -0.0370
2           52    0.9286                         0.7115       [0.5773, 0.8167]                                   0.7115                              0.6538             [0.518, 0.7685]                            -0.0577
3           50    0.8929                         0.7200       [0.5833, 0.8253]                                   0.7400                              0.6800            [0.5419, 0.7924]                            -0.0400
4           48    0.8571                         0.7292         [0.59, 0.8343]                                   0.7500                              0.6667            [0.5254, 0.7832]                            -0.0625
5           46    0.8214                         0.7391        [0.5974, 0.844]                                   0.7609                              0.6957            [0.5519, 0.8092]                            -0.0435
6           44    0.7857                         0.7727       [0.6301, 0.8716]                                   0.7500                              0.7273            [0.5815, 0.8365]                            -0.0455
7           42    0.7500                         0.8095        [0.667, 0.9002]                                   0.7857                              0.7143            [0.5643, 0.8283]                            -0.0952
8           40    0.7143                         0.8000        [0.6524, 0.895]                                   0.7750                              0.7250            [0.5716, 0.8389]                            -0.0750
9           38    0.6786                         0.8158       [0.6658, 0.9078]                                   0.7632                              0.7368            [0.5799, 0.8503]                            -0.0789
10          36    0.6429                         0.8611       [0.7134, 0.9392]                                   0.7778                              0.7500            [0.5893, 0.8625]                            -0.1111
11          34    0.6071                         0.8529       [0.6987, 0.9355]                                   0.7941                              0.7647               [0.6, 0.8756]                            -0.0882
12          32    0.5714                         0.9062       [0.7578, 0.9676]                                   0.8125                              0.7500            [0.5789, 0.8675]                            -0.1562
13          30    0.5357                         0.9032        [0.751, 0.9665]                                   0.8667                              0.7667            [0.5907, 0.8821]                            -0.1366

cascade 가 semantic-only 를 한 번도 못 이긴다: True

rule 이 확정한 11건에서의 짝 대조:
{
 "n": 11,
 "rule_agrees_with_prior": 6,
 "semantic_agrees_with_prior": 8,
 "rule_only_right_b": 0,
 "semantic_only_right_c": 2,
 "mcnemar_exact_p_two_sided": 0.5,
 "reading": "b=0 은 '규칙이 맞고 semantic 이 틀린 target 이 하나도 없다'는 뜻이다. 즉 이 표본에서 rule stage 는 semantic 이 이미 되찾는 업종 배정 위에 아무것도 얹지 못한다. n=11 이라 유의하지 않다."
}

![coverage](../../research_d/figures/RF2_F_coverage_tradeoff.png)

## 4. semantic confidence trap — 이 종합에서 가장 불편한 관측

In [9]:
t = O["target_property_sets"]["semantic_confidence_trap"]
print(json.dumps(t, ensure_ascii=False, indent=1))

{
 "question": "rule 이 전부 실패했는데 semantic margin 이 높은 target 은 semantic 을 더해야 하는 target 인가, 아니면 브랜드면인가?",
 "n_semantic_confident_but_no_rule_fires": 14,
 "of_which_surface_absent": 10,
 "of_which_capture_defect_only": 2,
 "of_which_genuinely_definition_ambiguous": 2,
 "surface_absent_services": [
  "Chrome",
  "GS25",
  "NH스마트뱅킹",
  "NH콕뱅크",
  "emart24",
  "디바이스 케어",
  "롯데하이마트",
  "마켓컬리",
  "신한 SOL뱅크",
  "캐시워크"
 ],
 "genuine_services": [
  "G마켓",
  "당근"
 ],
 "reading": "**이것이 이 종합에서 가장 불편한 관측이다.** semantic 이 가장 확신하는 미확정 target 의 대다수가 표면부재(브랜드면·앱설치면·미렌더) target 이다. E 가 이미 경고한 것과 같다 — 브랜드면의 텍스트는 그 서비스의 **업종**을 강하게 말해 주므로 semantic 이 잘 맞는데, 그것은 대표기능을 식별한 것이 아니다(D-FACT-01). 따라서 '규칙이 실패한 곳에 semantic 을 붙이면 coverage 가 는다' 는 처방은 **정확히 붙이면 안 되는 곳에 붙는다.**"
}

## 5. 어떤 종류의 ABSTAIN 인가 — 처방이 정반대인 세 갈래

In [10]:
ps = O["target_property_sets"]
rowsx = []
for k, v in ps.items():
    if k == "semantic_confidence_trap":
        continue
    rowsx.append({"set": k, "n": v["n"], "share": v["share_of_56"],
                  "blob_tok(med)": v["median_blob_tokens"], "n_fired(med)": v["median_E_n_fired"],
                  "margin(med)": v["median_E_sem_margin"], "prior": v["prior_archetype_distribution"]})
display(pd.DataFrame(rowsx))
print("\n원칙적 ABSTAIN (표면부재):", ps["principled_abstain_surface_absent"]["services"])
print("\n잘못된 종류의 ABSTAIN (재수집 대상):", ps["wrong_kind_of_abstain_capture_defect_only"]["services"])
print("\n정의 문제:", ps["residual_definition_ambiguity"]["services"])

                                         set   n   share  blob_tok(med)  n_fired(med)  margin(med)                                                                                      prior
0       deterministically_identifiable_union  31  0.5536          177.0           2.0       0.0327  {'ITEM_DETAIL': 18, 'CONTENT_OPEN': 3, 'PLACE_LOOKUP': 4, 'COMMUNICATION_ENTRY': 2, 'F...
1  undetermined_by_every_rule_implementation  25  0.4464          101.0           1.0       0.0190  {'FINANCIAL_ACTION_ENTRY': 7, 'ITEM_DETAIL': 8, 'QUERY': 3, 'UTILITY_ENTRY': 5, 'COMMU...
2                    needs_semantic_evidence  14  0.2500          205.0           1.5       0.0323  {'FINANCIAL_ACTION_ENTRY': 4, 'ITEM_DETAIL': 5, 'QUERY': 2, 'UTILITY_ENTRY': 2, 'COMMU...
3          principled_abstain_surface_absent  14  0.2500          195.0           0.5       0.0199  {'ITEM_DETAIL': 5, 'FINANCIAL_ACTION_ENTRY': 3, 'UTILITY_ENTRY': 4, 'COMMUNICATION_ENT...
4  wrong_kind_of_abstain_capture_defect_only   9  0.1607          325.0           2.0       0.0072            {'FINANCIAL_ACTION_ENTRY': 4, 'QUERY': 2, 'UTILITY_ENTRY': 1, 'ITEM_DETAIL': 2}
5              residual_definition_ambiguity   2  0.0357           98.5           3.0       0.0598                                               {'COMMUNICATION_ENTRY': 1, 'ITEM_DETAIL': 1}

원칙적 ABSTAIN (표면부재): ['GS25', '신한 SOL뱅크', '디바이스 케어', '마켓컬리', '카카오톡', 'Chrome', 'emart24', '캐시워크', '롯데하이마트', 'NH스마트뱅킹', '에이닷 전화', '배달의민족', '내 파일', 'NH콕뱅크']

잘못된 종류의 ABSTAIN (재수집 대상): ['삼성카드', '다음', 'V3 Mobile Plus', '네이버', '현대카드', '농협하나로마트', '하나은행', '이마트', '모니모']

정의 문제: ['당근', 'G마켓']

![abstain](../../research_d/figures/RF2_F_abstain_partition.png)

## 6. 세 축 독립 노출도 — C 의 경고를 정량화
> phi < 0 = 접근성 표면이 빈곤할수록 detector 가 abstain 한다 = 두 축이 함께 무너진다.
> n=56 에서 잡음 규모는 약 ±0.134 다. **후보 간 상대 비교로만** 읽는다.

In [11]:
lk = O["three_axis_independence_exposure"]
print(lk["_reading"], "\n")
display(pd.DataFrame({k: v for k, v in lk.items() if not k.startswith("_")}).T[
    ["n_determined", "phi_determined_vs_aria_labels_empty", "perm_p_aria",
     "phi_determined_vs_control_surface_empty", "perm_p_control_surface",
     "determination_rate_when_aria_empty", "determination_rate_when_aria_present"]])

phi < 0 = 접근성 표면이 빈곤할수록 detector 가 abstain 한다 = 두 축이 함께 무너진다. n=56 에서 |phi| 의 잡음 규모는 대략 1/sqrt(56) = 0.134 다. perm_p 와 함께만 읽어라. 절대값이 아니라 **후보 간 상대 노출도**로만 쓴다.

,n_determined,phi_determined_vs_aria_labels_empty,perm_p_aria,phi_determined_vs_control_surface_empty,perm_p_control_surface,determination_rate_when_aria_empty,determination_rate_when_aria_present
H1_rule_only_unique_strong,13,0.0315,0.8768,-0.1722,0.2789,"[5, 20]","[8, 36]"
H1_alt_ruleDT_leaf,11,0.0067,0.9777,-0.1548,0.5394,"[4, 20]","[7, 36]"
H2_rule_then_semantic_margin,40,0.1414,0.2877,0.0594,0.9866,"[16, 20]","[24, 36]"
H2_semantic_only_margin,34,0.1417,0.2742,0.1236,0.4548,"[14, 20]","[20, 36]"
H3_hierarchical_rule,16,-0.2239,0.0874,-0.198,0.2897,"[3, 20]","[13, 36]"

![leakage](../../research_d/figures/RF2_F_leakage_exposure.png)

## 7. RECOMMENDED_EXPERIMENTAL_CANDIDATES
> 순위 없음. 반증된 후보도 지우지 않는다.

In [12]:
for c in O["recommended_experimental_candidates"]:
    print("=" * 96)
    print(f"{c['candidate_id']}  {c['name']}")
    print(f"  status  : {c['status']}")
    print(f"  det/sem : {c['deterministic_portion']}  ||  {c['semantic_portion']}")
    print(f"  complexity  : {c['operational_complexity']}")
    print(f"  explainability: {c['explainability']}")
    print(f"  leakage : {c['leakage_risk']['level']}")
    print(f"  cost    : {c['cost']}")
    print(f"  -- 지지 {len(c['supported_by'])}건 / 반증 {len(c['refuted_by'])}건")
    for s in c["refuted_by"]:
        print(f"     REFUTE [{s['child']}] {s['evidence'][:170]}")
print("=" * 96)

================================================================================================
H1  High-precision Rule → unresolved = ABSTAIN
  status  : RETAINED_WITH_KNOWN_REFUTING_EVIDENCE
  det/sem : 전부. SSOT 01 §5 Stage-3 branch 의 REGION∧ENDPOINT 술어와 §6 resolver(유일 후보만 확정).  ||  없음.
  complexity  : LOW — 학습 없음, 모델 없음, 결정론적, 전 단계 provenance 추적 가능.
  explainability: HIGH. 어느 술어가 어느 field 의 어느 어휘로 발화했는지 target 마다 남는다 (A 의 per_target.firing 이 그 형식이다).
  leakage : MEDIUM
  cost    : coverage 0.20~0.25. SSOT §10 의 holdout coverage >= 0.75 에 도달 불가.
  -- 지지 3건 / 반증 4건
     REFUTE [D-RF2-A] 유일 STRONG 후보가 나오는 target 은 13/56 = 0.232 뿐이고 STRONG multi 30/56 이 압도한다. exclusivity 는 7개 중 6개가 0.000 — WEAK+ 수준에서 어떤 archetype 도 혼자 켜지지 못한다. 즉 '유일 후보' 조건 자체가 이 증거에서 거의 성립
     REFUTE [D-RF2-A] 유일 STRONG 후보가 prior 와 일치한 것은 56건 중 **1건**이다. 유일성이 타당성을 뜻하지 않는다.
     REFUTE [D-RF2-B] 규칙이 딛고 선 16개 조작화 feature 중 BH-FDR(q<0.10)을 통과하는 것이 **0개**다. 8개는 permutation null 평균에도 못 미친다. 규칙 술어의 근거는 이 데이터가 아니라 도메인 지식이다.
     REFUTE [D-RF2-F] 세 독립 rule 구현(A / D_flat / E_ruleDT)이 모두 확정한 target 은 56건 중 **1건**이다. Jaccard 0.043~0.190, pairwise kappa 는 −0.16~+0.13 으로 우연 수준이다. '결정 가능한 target' 은 target 의 성질이 아니라 lexi
================================================================================================
H2  High-precision Rule → Semantic prototype ranking → margin low = ABSTAIN
  status  : RETAINED_WITH_PARTIAL_REFUTATION_OF_ITS_RULE_STAGE
  det/sem : 1단계 규칙(H1 과 동일) + Stage-0 게이트 + abstention leaf 배정.  ||  2단계 — 하나의 텍스트 representation 을 7개 frozen prototype 과 코사인 비교, top1−top2 margin 으로 게이트. 학습 없음(zero-shot).
  complexity  : MEDIUM — 임베딩 모델 1개 + prototype 7문장 + 게이트 1개. 학습은 여전히 없음.
  explainability: MEDIUM. 1단계는 술어 provenance 가 남지만 2단계는 코사인 순위라 '왜 이 archetype 인가'를 field 수준으로 되짚을 수 없다. C 의 LOO ablation 이 사후 해부의 유일한 경로다.
  leakage : LOW_TO_MEDIUM
  cost    : coverage 를 얻는 대신 '무엇을 관측했는가'가 흐려진다. 그리고 D-FACT-01 때문에 이 후보의 관측된 이득은 **업종 배정 재현율의 이득**으로만 확인됐다.
  -- 지지 4건 / 반증 5건
     REFUTE [D-RF2-F] **이 후보의 1단계가 반증된다.** 같은 coverage 로 맞추면 rule-first cascade 가 semantic-only 를 **한 번도 이기지 못한다**(모든 대조점에서 Δ ≤ 0). rule 이 실제로 확정한 11건에서 McNemar b=0, c=2 — 규칙이 맞고 semantic 이 틀린
     REFUTE [D-RF2-C] margin 은 field 를 가르지 못한다 — 22개 representation 전부 margin 중앙값이 0.016~0.036 의 좁은 띠다. 게다가 `form_labels` 는 39/56 이 비었는데 margin 은 평균보다 높다 — **정보가 없을수록 margin 이 커지는 역전**이 있다. ma
     REFUTE [D-RF2-E] SSOT §6 이 §7 로 보내라고 한 T03 다중강후보 6건에서 semantic 불일치율(0.67)이 rule(0.50)보다 **높다**. 즉 이 후보의 2단계가 1단계의 실패 유형을 실제로 가른다는 증거가 없다.
     REFUTE [D-RF2-B] prior 를 되찾는 신호의 상당 부분이 페이지 규모 축일 수 있다 — 16 feature 의 제1성분(33% 분산)이 규모이고 상위 feature `accessible_name_richness`(MI 0.264)는 domain 의미가 없는 구조량이다.
     REFUTE [D-RF2-F] **semantic confidence trap.** 규칙이 전부 실패했는데 semantic margin 이 높은 14건 중 10건이 표면부재(브랜드면·앱설치면·미렌더) target 이다. 즉 이 후보의 2단계가 열어 주는 coverage 는 **정확히 열면 안 되는 곳에서** 열린다 — 브랜드면 텍스트
================================================================================================
H3  Hierarchical Interaction Rule → field-specific semantic ranking → conflict = ABSTAIN
  status  : RETAINED_BUT_ALREADY_PARTIALLY_REFUTED — 목록에서 지우지 않는다
  det/sem : L1 primitive 판정 + L2 후보 제한 + 충돌 게이트.  ||  L2 — primitive member 로 제한된 후보 위의 field-specific 유사도 순위.
  complexity  : HIGH — 2층 규칙 + field 별 임베딩 + 충돌 게이트. 세 후보 중 가장 비싸다.
  explainability: MEDIUM-HIGH for L1 (술어 추적 가능), LOW for L2 (field 별 코사인). 단 두 층으로 나뉘어 실패 지점을 특정하기는 쉽다 — D 가 '병목은 L1' 이라고 말할 수 있었던 것이 이 구조 덕이다.
  leakage : HIGH — 세 후보 중 최대
  cost    : 가장 비싼 구조에 대해 **관측된 이득이 정확히 0** 이다. 그리고 그 구조를 제대로 만들려면 SSOT 의 archetype 정의를 먼저 손대야 한다.
  -- 지지 3건 / 반증 7건
     REFUTE [D-RF2-D] **핵심 반증.** 계층 이득이 0 이다. flat 과 hier 의 prior 일치 여부가 target 단위로 완전히 같다 — McNemar b=0, c=0. 늘어난 coverage 2건은 둘 다 prior 불일치라 prior_agreement 는 5/56 → 5/56 으로 불변이다.
     REFUTE [D-RF2-D] 병목은 L1 이다. Stage0 6 / L1 무후보 19 / L1 다중후보 15 로 40건을 L1 에서 잃고 L2 에서는 0건을 잃는다. 계층을 넣어도 손실 구조가 바뀌지 않는다.
     REFUTE [D-RF2-D] L1 은 쉽지 않다. L1 이 닫은 16건의 prior primitive 일치 9/16=0.5625 는 같은 16건의 다수결 기준선 13/16=0.8125 **보다 낮다**.
     REFUTE [D-RF2-D] L1 의 후보 제한이 semantic arm 에서 정보를 **뺀다**: 동일 16건에서 제한 없는 7-way argmax 9/16 → 제한 후 6/16 (McNemar p=0.375, 방향은 음).
     REFUTE [D-RF2-D] SSOT §5 branch tree 는 primitive 위의 분할이 아니다 — PLACE_LOOKUP 과 COMMUNICATION_ENTRY 가 primitive 2개에 걸친다. 계층을 엄격히 강제하면(S2s) flat 이 확정하던 3건을 그 이유만으로 잃는다.
     REFUTE [D-RF2-C] **field-specific semantic 이 반증된다.** primary_controls 0.254 · first_screen_interaction 0.257 · accessibility_text 0.224 로 text_blob 0.509 의 절반 이하이며, 세 모델 모두에서 하위권이다. blob
     REFUTE [D-RF2-A] L1 이 겨냥한 list-family 얽힘은 국소 문제가 아니다 — family 6쌍의 평균 Jaccard(STRONG 0.145 / WEAK+ 0.548)가 나머지 15쌍(0.213 / 0.581)보다 오히려 **낮다**. 최강 얽힘 쌍은 F–U, Q–U 로 family 를 가로지른다.
================================================================================================
H4  Evidence-admissibility gate → single semantic ranking → margin low = ABSTAIN (rule 단계 없음)
  status  : NEW_CANDIDATE_ADDED_BY_SYNTHESIS
  det/sem : evidence admissibility 만 — Stage-0, E 의 표면부재/관측손상 유형 판정, 인코딩 검증. archetype 선택에는 규칙을 쓰지 않는다.  ||  단일 representation × 7 frozen prototype × margin 게이트.
  complexity  : LOW-MEDIUM — 규칙 트리가 없고 게이트 + 임베딩 1개.
  explainability: LOW. 게이트는 설명되지만 archetype 선택은 코사인 순위 하나다.
  leakage : LOW for accessibility-axis coupling, HIGH for identity circularity
  cost    : provenance 와 구조 증거를 통째로 포기한다. 그 대가로 이 표본에서 가장 높은 업종 재현율을 얻는다.
  -- 지지 3건 / 반증 4건
     REFUTE [D-RF2-E] **가장 무거운 반증.** 표면부재 유형을 먼저 abstain 시킨 캐스케이드는 같은 coverage 에서 prior_agreement 가 오히려 **낮다**. 브랜드/앱 랜딩면에서는 semantic 이 잘 맞는데, 그건 대표기능을 읽어서가 아니라 **업종을 맞혀서**다. 즉 이 후보의 게이트는 지표를
     REFUTE [D-RF2-C] semantic 단독의 신호는 identity 순환에 취약하다. `title` 0.559 → 브랜드 마스킹 0.357, `url_tokens` 0.361 → 0.138. 규칙을 빼면 이 순환을 견제할 구조가 하나도 남지 않는다.
     REFUTE [D-RF2-A] 규칙 단계를 빼면 '어떤 관측 때문에 이렇게 판정했는가'의 provenance 가 사라진다. A 의 per-target signal provenance 가 가능했던 것은 규칙이 있었기 때문이다.
     REFUTE [D-RF2-B] 구조 feature 가 판정에 전혀 들어가지 않으므로, 텍스트가 손상된 target 에서 대안이 없다.
================================================================================================

![candidates](../../research_d/figures/RF2_F_candidate_evidence.png)

## 8. 종합질문 5개

In [13]:
q = O["synthesis_questions"]
print("[Q1 master]\n", O["master_rq_answer"]["answer_in_one_paragraph"], "\n")
print("[Q2 deterministic 으로 식별 가능한 target 의 성질]\n", q["Q2_properties_of_deterministically_identifiable_targets"]["answer"], "\n")
print("[Q3 semantic 을 더해야 하는 target]\n", q["Q3_properties_of_targets_needing_semantic_evidence"]["answer"])
print("\n[Q3 보정]\n", q["Q3_properties_of_targets_needing_semantic_evidence"]["corrected_answer"], "\n")
print("[Q4 원칙적 ABSTAIN]\n", q["Q4_principled_abstain"]["answer"])

[Q1 master]
 L0 landing snapshot 하나를 관측하면 **그 페이지가 지금 무엇을 하게 해 주는지에 대한 약한 증거**와 **그 서비스가 어느 업종인지에 대한 비교적 강한 증거**를 얻는다. 대표기능은 얻지 못한다. 이 구분이 가능한 이유는 세 가지 관측이 같은 방향을 가리키기 때문이다 — (1) D-RF2-D 의 L1 이 확정한 7건 중 6건이 QUERY 로 흡수됐고 prior 가 QUERY 인 것은 1건뿐이다(랜딩에서 가장 완결된 affordance 가 검색창이기 때문이다), (2) D-RF2-A 에서 유일 STRONG 후보 = prior 인 target 이 56건 중 1건뿐이다, (3) D-RF2-C 에서 브랜드 문자열을 지우면 title 의 우위가 0.559→0.357 로 무너진다. 그리고 D-FACT-01 때문에 (2)(3)의 '맞았다/틀렸다'는 전부 **업종 배정**에 대한 것이다. 따라서 정직한 답은: **관측하면 업종을 알 수 있고, 랜딩이 제공하는 affordance 를 부분적으로 알 수 있으며, 대표기능은 이 증거만으로는 알 수 없다.**

[Q2 deterministic 으로 식별 가능한 target 의 성질]
 **결정적 증거만으로 식별 가능한 target 의 가장 두드러진 성질은 '그 성질이 target 이 아니라 lexicon 에 있다' 는 것이다.** 세 독립 rule 구현(A 13건 / D_flat 14건 / E_ruleDT 11건)의 합집합은 31건인데 교집합은 **1건**이다. Jaccard 는 0.043~0.190, pairwise kappa 는 −0.16~+0.13 으로 우연 수준이다. 같은 SSOT §5·§6 를 어휘만 바꿔 구현하면 다른 target 집합이 열린다. 그 위에서 관측되는 부차적 성질은: 텍스트가 충분히 있고(blob 토큰 중앙값 177.0 vs 미확정 101.0), 술어가 하나 이상 발화하며(E n_fired 중앙값 2 vs 1), semantic margin 도 이미 높다(중앙값 0.0327 vs 0.019). **즉 규칙이 닫는 target 은 semantic 도 이미 닫는 target 이다** — 이것이 Q5 의 답으로 이어진다.

[Q3 semantic 을 더해야 하는 target]
 semantic 을 더해야 하는 target 은 **표면이 관측됐고 손상도 없는데 술어가 배타적으로 발화하지 못한 target** 이다. E 의 유형으로 말하면 T02(한쪽 신호만, abstain 40 중 22 — 최대 유형)와 T03(다중 강후보 6)이다. 이들에서 semantic force-map 불일치는 T02 0.23 으로 rule 0.68 의 1/3 이다 — semantic 이 실제로 보탠다. **반대로 semantic 을 더해도 안 되는 것이 T03 이다**: rule 0.50 vs semantic 0.67 로 semantic 이 더 나쁘다. SSOT §6 이 다중후보를 §7 로 보내라고 규정했는데, 이 표본에서 §7 이 그 6건을 더 못 가른다. n=6 이라 결론은 아니지만 **'semantic 이 ambiguity 를 푼다'는 전제가 검증되지 않았다는 사실 자체가 결과다.**

[Q3 보정]
 위 trap 을 반영하면 Q3 의 답은 좁아진다. rule 이 전부 실패했는데 semantic margin 이 높은 14건 중 10건이 **표면부재 target** 이고 진짜로 정의상 애매해서 semantic 이 필요한 것은 2건뿐이다(['G마켓', '당근']). **즉 'semantic evidence 를 더해야 하는 target' 은 이 코호트에서 극소수다.** semantic 이 열어 주는 coverage 의 대부분은 대표기능이 아니라 업종을 읽어서 열린다.

[Q4 원칙적 ABSTAIN]
 세 rule 구현이 모두 확정에 실패한 25건을 원인으로 가르면: **표면부재 14건** (그 중 T07 미렌더·error 5건, 그리고 14건 중 10건은 관측손상까지 겹쳐 재수집해도 없는 표면이 생기지 않는다), **관측손상만 9건** (재수집 대상 — 이것은 '미결정'이 아니라 '아직 안 봤다'이며 지금의 abstain 은 잘못된 종류다), **둘 다 아닌 정의 문제 2건**. 따라서 **현재 evidence 로 원칙적으로 식별 불가능해서 ABSTAIN 이 정직한 target 은 14건(하한)** 이고, SSOT 정의를 고치지 않는 한 못 푸는 것까지 포함하면 16건이다. 이유는 detector 결함이 아니라 **target URL 이 그 서비스의 기능면이 아니라 그것을 설명하는 면**이기 때문이다 — E 의 처방은 detector 개선이 아니라 target URL 감사다.

In [14]:
s = O["smallest_sufficient_structure"]
print("[Q5 가장 작은 충분구조]\n", s["answer"], "\n")
display(pd.DataFrame(s["minimum_viable_stack"]))
print("\nTHE CATCH\n", s["the_catch"], "\n")
print("규칙 트리는 무엇에 쓰는가\n", s["what_the_rule_tree_is_still_for"])

[Q5 가장 작은 충분구조]
 **두 단계면 된다: (1) evidence admissibility 게이트, (2) 하나의 텍스트 representation 위의 7-prototype 유사도 + margin 게이트.** archetype 을 고르는 규칙 트리는 이 표본에서 그 위에 아무것도 얹지 못한다 — 같은 coverage 로 맞추면 rule-first cascade 가 semantic-only 를 한 번도 이기지 못하고(모든 대조점에서 Δ ≤ 0), rule 이 실제로 확정한 11건에서 McNemar b=0 (규칙이 맞고 semantic 이 틀린 target 이 0건), c=2 다. evidence 쪽 최소치도 작다 — C 에 따르면 `identity`(title + meta_description + url_tokens, 중앙값 29토큰)가 `text_blob`(498토큰)과 같은 prior_agreement 38/56 를 내고 macro F1 은 더 높다. **토큰을 17배 줄여도 손해가 없다.**

   stage                                                         name           kind                                                            why                                                     cost
0      1                                        Stage-0 renderability  deterministic                 SSOT §2 가 이미 확정을 금지한다. 이 코호트 56 중 5건이 여기서 걸린다.                                                     거의 0
1      2               evidence-defect gate (인코딩 · cap · 오버레이 · 렌더희소)  deterministic  E: 강제선택 불일치율이 인코딩 손상에서 1.00 이다. 이 게이트가 없으면 수집 결함이 연구결과로 세탁된다.                               관측표 플래그 4개. 이미 전부 관측되고 있다.
2      3  one text representation × 7 frozen prototypes × margin gate       semantic                            coverage 를 얻는 유일한 단계. 학습 없음, 모델 1개.  provenance 상실. threshold 는 calibration split 없이는 못 정한다.

THE CATCH
 이 '최소 충분구조'가 충분한 것은 **업종 배정 재현율**에 대해서다(D-FACT-01). 그리고 identity 로 좁힐수록 C 가 경고한 순환 — title/url 이 브랜드를 읽고 브랜드→업종→archetype 을 되짚는 경로 — 이 강해진다. C 의 브랜드 마스킹에서 `url_tokens` 0.361→0.138, `title` 0.559→0.357 이다. **따라서 최소 충분구조는 '가장 작다'와 '가장 순환적이다'가 같은 방향이다.** 독립 label 없이 이 구조를 채택하면 업종 분류기를 대표기능 detector 라고 부르게 된다. 더 구체적으로: 규칙이 전부 실패했는데 semantic 이 확신하는 14건 중 10건이 표면부재 target 이다(`synthesis_questions.Q3...semantic_confidence_trap`). semantic 단계가 벌어들이는 coverage 의 상당 부분이 **대표 기능면이 아닌 페이지에서** 나온다.

규칙 트리는 무엇에 쓰는가
 **버리라는 말이 아니다.** 규칙은 이 표본에서 archetype 선택에는 기여하지 않았지만 (a) provenance — 어느 field 의 어느 어휘가 발화했는지, (b) 반증 가능성 — D-RF2-D 가 '병목은 L1' 이라고 말할 수 있었던 것은 규칙이 있었기 때문, (c) prior 와 구조의 불일치 관측(E 의 T13 17건)을 제공한다. semantic-only 구조에는 이 세 가지가 전부 없다.

## 9. 반례 · limitation · 추가 연구질문

In [15]:
for c in O["counterexamples"]:
    print(f"[{c['kind']}]\n  {c['detail']}\n  -> {c['reading']}\n")

[세 구현이 모두 확정한 유일한 target — 그런데 prior 와 불일치]
  {'wtg': '4feab7e61bf642e8', 'service': 'CJ온스타일', 'prior_archetype': 'ITEM_DETAIL', 'A': 'QUERY', 'D': 'QUERY', 'E': 'QUERY'}
  -> '세 구현이 합의하면 믿을 만하다'는 직관의 반례다. 세 독립 lexicon 이 모두 QUERY 로 닫았는데 prior 는 ITEM_DETAIL 이다. 합의는 타당성이 아니라 '랜딩에서 검색창이 가장 완결된 affordance' 라는 같은 편향의 공유일 수 있다.

[이 종합 자신의 결론에 대한 반례 — semantic-only 가 이기는 이유가 나쁜 이유다]
  D-RF2-F: 규칙이 전부 실패했는데 semantic margin 이 높은 14건 중 10건이 표면부재 target(Chrome · GS25 · NH스마트뱅킹 · NH콕뱅크 · emart24 · 디바이스 케어 · 롯데하이마트 · 마켓컬리 · 신한 SOL뱅크 · 캐시워크)이다.
  -> §'가장 작은 충분구조' 가 semantic-only 로 기운 근거는 coverage×prior_agreement 곡선인데, 그 곡선이 좋아지는 구간의 상당 부분이 브랜드면이다. **이 반례는 이 문서가 semantic-only 를 추천하지 않는 이유이기도 하다** — D 는 후보를 제시하고 대가를 적을 뿐 순위를 매기지 않는다.

[semantic 이 규칙보다 항상 나은 것은 아니다]
  D-RF2-E: T03_MULTI_STRONG_CANDIDATE 6건에서 semantic 불일치 0.67 > rule 0.50
  -> SSOT §6 → §7 캐스케이드의 핵심 전제(§7 이 다중후보를 가른다)가 이 표본에서 반증 방향이다.

[표면부재를 먼저 걸러내면 지표가 나빠진다]
  D-RF2-E: T05/T06/T07 을 먼저 abstain 시킨 캐스케이드는 같은 coverage 에서 prior_agreement 가 낮다
  -> 올바른 처방이 지표를 떨어뜨린다. 지표가 대표기능이 아니라 업종을 재고 있기 때문이다(D-FACT-01). **이 반례는 지표 자체를 반증한다.**

[control 표면이 이기는 2건]
  D-RF2-C §11: TikTok(prior CONTENT_OPEN — blob 은 COMMUNICATION_ENTRY, controls 는 CONTENT_OPEN), 네이버(prior QUERY — blob 은 ITEM_DETAIL, controls 는 QUERY)
  -> H3 의 field-specific 발상이 23:2 로 졌지만 0:25 는 아니다. 네이버 첫 화면 전체 텍스트는 쇼핑·뉴스 카드로 덮여 ITEM_DETAIL 로 끌려가는데 검색 버튼의 aria-label 은 QUERY 를 정확히 가리킨다. 'controls 가 무의미하다'는 반대 극단도 틀렸다.

[어떤 유형으로도 설명되지 않는 잔여]
  D-RF2-E: 컴포즈커피 1건 — blob 19토큰, dom_body_empty=0, 인코딩 정상인데 아무 유형에도 안 걸린다
  -> abstention taxonomy 의 완결성 상한. REAL_TARGET 규모에서 이 잔여가 몇 %인지는 미지수다.

In [16]:
print("LIMITATION (무거운 것부터)")
for i, l in enumerate(O["limitation"], 1):
    print(f" {i}. {l}\n")
print("NEXT RESEARCH QUESTIONS")
display(pd.DataFrame(O["next_research_questions"]))

LIMITATION (무거운 것부터)
 1. **가장 무겁다 — 이 종합의 모든 정량 대조가 prior 를 기준으로 한다.** D-FACT-01 에 따라 prior_archetype 은 prior_business_domain 과 전단사이므로 모든 수치는 업종 배정 재현율이다. 'semantic-only 가 cascade 를 이긴다'는 **업종을 더 잘 되찾는다**는 뜻이며, 대표기능에 대해서는 어느 후보가 나은지 이 표본으로 **원리적으로** 말할 수 없다. 후보 선택은 gold label 없이 닫히지 않는다.

 2. 이 문서는 새 실험을 하지 않았다. A~E 의 산출물을 교차 종합한 2차 분석이며, 각 child 의 조작화(어휘사전·임계·prototype·유형 판정식)를 그대로 상속한다. 그 조작화가 틀렸다면 이 종합도 같이 틀린다.

 3. 세 rule 구현의 낮은 일치도(kappa −0.16~+0.13)는 '규칙이 나쁘다'가 아니라 '세 구현이 서로 다르다'는 관측이다. 어느 구현이 SSOT §5 를 더 충실히 조작화했는지 D 는 판정할 수 없다 — 판정하려면 SSOT 해석의 권위가 필요하고 그것은 A 에 있다.

 4. n=56, 7 class 중 5개가 n≤5. 모든 하위집합 수치의 Wilson CI 가 넓다. 후보 간 coverage 차이는 대부분 CI 가 겹친다.

 5. semantic 축 수치는 E 가 독립 재계산한 bge-m3 × A_SSOT_DEF × text_blob 하나에 의존한다. C 는 e5-small 에서 field 효과가 prototype 노이즈에 묻힌다고 보고했다 — 모델을 바꾸면 결론이 흔들린다.

 6. leakage 노출 phi 는 n=56 에서 잡음 규모 ±0.13 과 겹친다. **후보 간 상대 비교로만** 읽어야 하고, 'H3 가 위험하다'는 정량 확증이 아니라 C 의 정성 경고에 방향이 일치한다는 관측이다.

 7. E 의 해결가능성 판정(RESOLVABLE / UNDECIDABLE)은 반사실 주장이며 재수집 실험 전에는 가설이다. Q4 의 '원칙적 ABSTAIN 14건' 은 그 가설 위에 서 있다.

 8. endpoint 를 정적 presence 로 강등한 것이 A·D·E 세 구현에 공통으로 들어 있다. 이 강등은 coverage 를 낙관적으로 올리는 방향이며, 상호작용 기반 endpoint 로는 세 구현 모두 coverage 가 줄고 no-evidence 가 는다.

 9. 이 문서는 production threshold 를 정하지 않았고 GO/NO-GO 를 내지 않았으며 best model 을 고르지 않았다.

NEXT RESEARCH QUESTIONS

               id                                                                                          q                                                         why
0  RQ-D-RF-002-f1  세 rule 구현의 확정집합이 거의 겹치지 않는다(J 0.043~0.190). 이 불일치를 lexicon 축으로 분해할 수 있는가 — 세 구현의 어휘 교집...  '결정 가능한 target' 이 lexicon 의 성질인지 target 의 성질인지를 가르는 직접 실험.
1  RQ-D-RF-002-f2  prior 가 아닌 기준으로 후보를 비교할 수 있는가 — representation·모델·prototype 을 바꿔도 예측이 안 바뀌는 target 집합(...    D-SUP-01 이 이미 이 방향으로 갔다. 후보 비교의 유일한 prior-free 경로일 수 있다.
2  RQ-D-RF-002-f3                    규칙 단계를 뺐을 때 실제로 잃는 것(provenance · 반증가능성 · prior-구조 불일치 관측)을 정량화할 수 있는가?  Q5 의 '최소 충분구조' 는 지표상 손해가 없지만 관측력에서는 손해다. 그 손해가 얼마인지는 안 쟀다.
3  RQ-D-RF-002-f4           업종 어휘까지 마스킹한 조건에서 semantic 이 남기는 신호는 무엇인가? (C 의 최우선 후속질문. 브랜드 문자열만 지운 절제는 조악하다.)                 'semantic 인가 identity 인가' 를 닫는 유일한 D-내부 경로.
4  RQ-D-RF-002-f5                           표면부재 14건의 target URL 을 재정의하면 몇 건이 확정 가능해지는가? (E 의 target URL 감사)      coverage 를 올리는 첫 시도가 detector 개선이 아니라 모집단 정의라는 주장의 검증.
5  RQ-D-RF-002-f6  접근성 표면을 분류 feature 에서 완전히 배제한 detector 와 포함한 detector 를 같은 코호트에서 돌렸을 때, KWCAG 축 점수와 de...           세 축 독립 위반은 현재 phi 관측(잡음 규모와 겹침)뿐이다. 설계된 대조가 필요하다.

In [17]:
print("VERDICT:", O["verdict"])
print(O["verdict_note"])
print("\nMLflow run:", META["mlflow"]["run_id"], "(parent", META["mlflow"]["parent_run_id"] + ")")

VERDICT: PARTIALLY_SUPPORTED
A~E 를 합치면 '무엇을 관측하면 무엇을 안다고 말할 수 있는가' 에 부분적으로만 답할 수 있다. 확실히 답할 수 있는 것: (1) 현재 L0 landing 증거로 **업종 배정**은 상당 부분 되찾을 수 있고, (2) **대표기능**을 안다고 말할 근거는 이 표본 안에 없다 — 두 라벨이 전단사라 구분이 원리적으로 불가능하다. 후보 architecture 3개는 모두 제출 가능하지만 셋 다 각각 다른 child 에게 반증당했고, 셋이 공유하는 '규칙 먼저' 전제는 이 표본에서 지지되지 않는다.

MLflow run: 3aa6b7dfb6c8444d8187c0c8f43e186b (parent ae754858ba3a4be391e5f811640d3fd8)